import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { HydrateAtoms, QueryProviders } from "@/providers/query-provider";
import { ToastProvider } from "@/providers/toast-provider";
import { Provider } from "jotai";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col bg-gray-100">
        <QueryProviders>
          <Provider>
            <HydrateAtoms>
              <ReactQueryDevtools initialIsOpen={false} />
              <ToastProvider />
              {children}
            </HydrateAtoms>
          </Provider>
        </QueryProviders>
      </body>
    </html>
  );
}
